import type { Metadata } from 'next'
import { Barlow_Semi_Condensed } from 'next/font/google'
import './globals.css'

const barlows = Barlow_Semi_Condensed({
  weight : ['500','600'],
  subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'testimonials-grid-section',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={barlows.className}>{children}</body>
    </html>
  )
}
